### PR TITLE
Improved Notices section

### PR DESCRIPTION
**Pull request by ghost**
FIXED
1. Used CSS marquee for the circular looping of the notices.
2. Different font colors for the date and notices providing better juxtaposition.

UNFIXED
1. Still unable to link the notices to their actual sites.
2. Unable to stop the animation when hovered over.

### CODE REVIEW

**Comment by hiiiideepak** [comment]
Is http://sacportalazd.herokuapp.com/ the final app.
This doesn't seem to fix the issue :smile:

**Comment by ghost** [comment]
> 
> 
> Is http://sacportalazd.herokuapp.com/ the final app.
> This doesn't seem to fix the issue 😄

No Sir, it's not the final. I'm still working on perfecting it. It was just an improvement. Maybe you can close this pull request then, I'll reopen it when I've fixed the entire thing.

**Comment by hiiiideepak** [comment]
> > Is http://sacportalazd.herokuapp.com/ the final app.
> > This doesn't seem to fix the issue smile
> 
> No Sir, it's not the final. I'm still working on perfecting it. It was just an improvement. Maybe you can close this pull request then, I'll reopen it when I've fixed the entire thing.

Okay cool. Keep improving :+1:

**Review by hiiiideepak — COMMENTED** [review]
approved :+1: . not merged yet due to incomplete changes

**Pull request closed without merging**
